services:
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-dbest_moon}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-example}
    volumes:
      - ./data/dev/postgres:/var/lib/postgresql/data

  app:
    image: osu-courses/app:dev
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - database
    ports:
      - ${WEB_PORT:-3000}:3000
      - ${API_PORT:-8080}:8080
      - 4983:4983
      - 4440:4440
      - 4441:4441
      - 4442:4442
    tty: true
    init: true
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
    environment:
      WEB_PORT: 3000
      API_PORT: 8080
      DB_NAME: ${DB_NAME:-dbest_moon}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-example}
      DB_HOST: database
      DB_PORT: 5432
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
    volumes:
      - .:/app
      - ./data/dev/drizzle:/app/apps/api/drizzle
      - ./data/dev/moon_cache:/app/.moon/cache
      - ./data/dev/proto:/root/.proto
      - ./data/dev/node_modules/root:/app/node_modules/
      - ./data/dev/node_modules/api:/app/apps/api/node_modules/
      - ./data/dev/node_modules/web:/app/apps/web/node_modules/
      - ./data/dev/node_modules/api-client:/app/packages/api-client/node_modules/
      - ./data/dev/node_modules/ui:/app/packages/ui/node_modules/
